services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      CI: 'true'
    develop:
      watch:
        - action: restart
          path: package.json

volumes:
  app-node-modules:
